### ISSUE TITLE
Errors on webpage?

### ISSUE THREAD

**Issue by Foggy-J** [baisiK/R4P3_GroupAssigner#1]
When I navigate to the website, I am shown this error:
![Website Error](https://i.gyazo.com/75310e658918e48e8c104c17a30e9215.png)

And in the TeamSpeak, I have an error icon:
![TeamSpeak Error](https://i.gyazo.com/8dc17eee3939935778a1043c41cece1a.png)

**Comment by baisiK** [comment]
I just fixed it.
